import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
//components
import HotelAmenities from '@/components/HotelAmenities/HotelAmenities'
import Guestrooms from '@/components/Guestrooms/Guestrooms'
import Hero from '@/components/Hero'
import Decoration from '@/components/Decoration/Decoration'
import PanelSection from '@/components/PanelSection/PanelSection'
import CheckAvailability from '@/components/CheckAvailability'
//redux
import { useSelector } from 'react-redux'


// library Semantic UI
// import 'semantic-ui-css/semantic.min.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	const heros = useSelector((state: any) => state.heros.value)

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<Hero>
					<CheckAvailability></CheckAvailability>
				</Hero>
				<HotelAmenities />
				<Guestrooms />
				<Decoration />
				<PanelSection />
				<Decoration />
			</main>
		</>
	)
}
